- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Allow rootless containers to use ports starting from 23
  ansible.builtin.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "{{ unprivileged_port_start }}"
    state: present
    sysctl_set: true

- name: Create proxy network
  containers.podman.podman_network:
    name: proxy

- name: Install caddy
  ansible.builtin.include_tasks:
    file: caddy.yml
